In [2]:
!pip install python-constraint

Requirement already satisfied: python-constraint in c:\users\laura\appdata\local\programs\python\python311\lib\site-packages (1.4.0)

In [52]:
import pandas as pd
from math import ceil
from constraint import Problem

In [5]:
vistaf1 = pd.read_csv('vista_fase1_rows.csv')
vistaf1.head(10)

,id,asignatura,credito_total,tipo_credito,horas_semanales,distribucion_horaria,distribucion_salon,prerrequisito,inscrito,porcentaje_aprobacion,porcentaje_retiro,porcentaje_reprobacion,estimados,num_grupos,codigo,carrera,semestre
0,192,CALCULO 1,3.0,3A,3.0,2 clases de 1:30 h,Salon Normal,PRECALCULO,77,69.3,7.7,2.4255,87.0,4.0,11310003,MA02,2.0
1,193,CALCULO 2,3.0,3A,3.0,2 clases de 1:30 h,Salon Normal,CALCULO 1,53,47.7,5.3,1.6695,60.0,3.0,11310004,MA02,3.0
2,196,CAPSTONE PROJECT,3.0,3B,9.0,NaN,"208 Casur, (Tesla)","OPTIMIZACION, KEYSTONE PROJECT, ANALISIS DE SI...",28,25.2,2.8,0.8820,32.0,2.0,11310029,MA02,8.0
3,184,ANALISIS DE SISTEMAS DE POTENCIA,3.0,2A + 1B,5.0,"1 clase de 2:00 h, 1 clase de 3:00 h",Laboratorio,"ELEMENTOS DE SISTEMAS ELECTRICOS, ECUACIONES D...",2,1.8,0.2,0.0630,2.0,1.0,32710007,ISE1,NaN
4,182,ALGORITMOS Y ESTRUCTURAS DE DATOS,3.0,2A + 1B,5.0,"1 clase de 2:00 h, 1 clase de 3:00 h",Sala de computo,PROGRAMACION DE COMPUTADORES,47,42.3,4.7,1.4805,53.0,3.0,11310006,MA02,2.0
5,186,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA,3.0,3A,3.0,2 clases de 1:30 h,Salon con computadores,"ALGEBRA LINEAL, ALGORITMOS Y ESTRUCTURAS DE DA...",47,42.3,4.7,1.4805,53.0,3.0,11310021,MA02,7.0
6,197,CIBERSEGURIDAD,2.0,1A + 1B,4.0,2 clases de 2:00 h,Sala de computo,INGENIERIA DE DATOS,13,11.7,1.3,0.4095,15.0,1.0,11310049,NaN,NaN
7,189,ARQUITECTURA DEL COMPUTADOR,3.0,2A + 1B,5.0,"1 clase de 2:00 h, 1 clase de 3:00 h","1 clase en salon normal, 1 clase en sala de co...",PROGRAMACION DE COMPUTADORES,11,9.9,1.1,0.3465,12.0,1.0,11320002,MA03,NaN
8,227,INTRODUCCION AL PROCESAMIENTO DEL LENGUAJE NAT...,3.0,2A + 1B,5.0,"1 clase de 2:00 h, 1 clase de 3:00 h",Sala de computo,APRENDIZAJE AUTOMATICO DE MAQUINAS,17,15.3,1.7,0.5355,19.0,1.0,11320031,MA01-MA02-MA03,NaN
9,224,INGENIERIA DE DATOS,3.0,2A + 1B,5.0,"1 clase de 2:00 h, 1 clase de 3:00 h",Sala de computo,"PROGRAMACION DE COMPUTADORES, ALGORITMOS Y EST...",56,50.4,5.6,1.7640,63.0,3.0,11310017,MA02,3.0

In [6]:
vistaf1 = vistaf1.fillna(0)
vistaf1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      83 non-null     int64
 1   asignatura              83 non-null     object
 2   credito_total           83 non-null     float64
 3   tipo_credito            83 non-null     object
 4   horas_semanales         83 non-null     float64
 5   distribucion_horaria    83 non-null     object
 6   distribucion_salon      83 non-null     object
 7   prerrequisito           83 non-null     object
 8   inscrito                83 non-null     int64
 9   porcentaje_aprobacion   83 non-null     float64
 10  porcentaje_retiro       83 non-null     float64
 11  porcentaje_reprobacion  83 non-null     float64
 12  estimados               83 non-null     float64
 13  num_grupos              83 non-null     float64
 14  codigo                  83 non-null     int64
 15  carrera                 83 non-null     object
 16  semestre                83 non-null     float64
dtypes: float64(8), int64(3), object(6)
memory usage: 11.1+ KB

In [90]:
df = pd.DataFrame(columns=['programa', 'codigo', 'semestre', 'asignatura', 'codificacion', 'horario'])
for i in range(len(vistaf1)):
    if vistaf1.num_grupos[i] != 0 and vistaf1.carrera[i] == "MA02" :
        num = int(vistaf1.horas_semanales[i])
        num = num if num <= 6 else 1
        num_semanal = ceil(num/2)
        #print(vistaf1.asignatura[i],num, num_semanal)
        for j in range(num_semanal):
            df.loc[len(df)] = [vistaf1.carrera[i], vistaf1.codigo[i], vistaf1.semestre[i], vistaf1.asignatura[i], vistaf1.asignatura[i]+"_"+str(j+1), ""]
# Mostrar el DataFrame
df.head(10)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310003,2.0,CALCULO 1,CALCULO 1_1,
1,MA02,11310003,2.0,CALCULO 1,CALCULO 1_2,
2,MA02,11310004,3.0,CALCULO 2,CALCULO 2_1,
3,MA02,11310004,3.0,CALCULO 2,CALCULO 2_2,
4,MA02,11310029,8.0,CAPSTONE PROJECT,CAPSTONE PROJECT_1,
5,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,ALGORITMOS Y ESTRUCTURAS DE DATOS_1,
6,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,ALGORITMOS Y ESTRUCTURAS DE DATOS_2,
7,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,ALGORITMOS Y ESTRUCTURAS DE DATOS_3,
8,MA02,11310021,7.0,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA_1,
9,MA02,11310021,7.0,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA_2,

In [92]:
df_1 = df[df.semestre == 1].reset_index(drop=True)
df_2 = df[df.semestre == 2].reset_index(drop=True)
df_3 = df[df.semestre == 3].reset_index(drop=True)
df_4 = df[df.semestre == 4].reset_index(drop=True)
df_5 = df[df.semestre == 5].reset_index(drop=True)
df_6 = df[df.semestre == 6].reset_index(drop=True)
df_7 = df[df.semestre == 7].reset_index(drop=True)
df_8 = df[df.semestre == 8].reset_index(drop=True)

In [93]:
dict_horario = {
    0: "7:00 - 9:00 | Lunes",
    1: "7:00 - 9:00 | Martes",
    2: "7:00 - 9:00 | Miércoles",
    3: "7:00 - 9:00 | Jueves",
    4: "7:00 - 9:00 | Viernes",
    5: "9:00 - 11:00 | Lunes",
    6: "9:00 - 11:00 | Martes",
    7: "9:00 - 11:00 | Miércoles",
    8: "9:00 - 11:00 | Jueves",
    9: "9:00 - 11:00 | Viernes",
    10: "11:00 - 13:00 | Lunes",
    11: "11:00 - 13:00 | Martes",
    12: "11:00 - 13:00 | Miércoles",
    13: "11:00 - 13:00 | Jueves",
    14: "11:00 - 13:00 | Viernes",
    15: "13:00 - 15:00 | Lunes",
    16: "13:00 - 15:00 | Martes",
    17: "13:00 - 15:00 | Miércoles",
    18: "13:00 - 15:00 | Jueves",
    19: "13:00 - 15:00 | Viernes",
    20: "15:00 - 17:00 | Lunes",
    21: "15:00 - 17:00 | Martes",
    22: "15:00 - 17:00 | Miércoles",
    23: "15:00 - 17:00 | Jueves",
    24: "15:00 - 17:00 | Viernes",
    25: "17:00 - 19:00 | Lunes",
    26: "17:00 - 19:00 | Martes",
    27: "17:00 - 19:00 | Miércoles",
    28: "17:00 - 19:00 | Jueves",
    29: "17:00 - 19:00 | Viernes"
}
print(dict_horario[0])

7:00 - 9:00 | Lunes

In [94]:
horarios_mañana = list(range(19, -1, -1))
print(horarios_mañana)
horarios_tarde = list(range(29, 19, -1))
print(horarios_tarde)

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[29, 28, 27, 26, 25, 24, 23, 22, 21, 20]

In [108]:
def no_overlap(a, b):
    """ Verifica que dos clases no se solapen en horario """
    return a != b

def generate_schedule(df, horarios):
    """
    Genera un horario para las clases especificadas en el DataFrame df,
    utilizando la lista de horarios proporcionada.
    
    Args:
        df: DataFrame que contiene las clases y sus codificaciones.
        horarios: Lista de horarios disponibles.
    
    Returns:
        Diccionario de solución que asigna horarios a cada clase.
    """
    # Crear el problema CSP
    problem = Problem()
    
    # Añadir las variables (clases) y sus dominios (horarios)
    for clase in df['codificacion']:
        problem.addVariable(clase, horarios)
    
    # Añadir la restricción de no solapamiento
    for i in range(len(df)):
        for j in range(i + 1, len(df)):
            problem.addConstraint(no_overlap, (df['codificacion'][i], df['codificacion'][j]))
    
    # Obtener la solución
    solucion = problem.getSolution()
    solucion = {clase: dict_horario[horario] for clase, horario in solucion.items()}
    df['horario'] = df['codificacion'].apply(lambda x: solucion[x])
    return df

In [112]:
solucion_df1 = generate_schedule(df_1, horarios_mañana)
solucion_df1.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,PROGRAMACION DE COMPUTADORES_1,9:00 - 11:00 | Lunes
1,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,PROGRAMACION DE COMPUTADORES_2,9:00 - 11:00 | Martes
2,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,PROGRAMACION DE COMPUTADORES_3,9:00 - 11:00 | Miércoles
3,MA02,11310044,1.0,PRECALCULO,PRECALCULO_1,7:00 - 9:00 | Jueves
4,MA02,11310044,1.0,PRECALCULO,PRECALCULO_2,7:00 - 9:00 | Viernes
5,MA02,11310025,1.0,PENSAMIENTO MATEMATICO,PENSAMIENTO MATEMATICO_1,7:00 - 9:00 | Miércoles
6,MA02,11310001,1.0,LOGICA TEORIA DE NUMEROS Y CONJUNTOS,LOGICA TEORIA DE NUMEROS Y CONJUNTOS_1,7:00 - 9:00 | Lunes
7,MA02,11310001,1.0,LOGICA TEORIA DE NUMEROS Y CONJUNTOS,LOGICA TEORIA DE NUMEROS Y CONJUNTOS_2,7:00 - 9:00 | Martes

In [113]:
solucion_df2 = generate_schedule(df_2, horarios_mañana)
solucion_df2.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310003,2.0,CALCULO 1,CALCULO 1_1,7:00 - 9:00 | Jueves
1,MA02,11310003,2.0,CALCULO 1,CALCULO 1_2,7:00 - 9:00 | Viernes
2,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,ALGORITMOS Y ESTRUCTURAS DE DATOS_1,7:00 - 9:00 | Lunes
3,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,ALGORITMOS Y ESTRUCTURAS DE DATOS_2,7:00 - 9:00 | Martes
4,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,ALGORITMOS Y ESTRUCTURAS DE DATOS_3,7:00 - 9:00 | Miércoles
5,MA02,11310011,2.0,FUNDAMENTOS DE SISTEMAS DIGITALES,FUNDAMENTOS DE SISTEMAS DIGITALES_1,9:00 - 11:00 | Lunes
6,MA02,11310011,2.0,FUNDAMENTOS DE SISTEMAS DIGITALES,FUNDAMENTOS DE SISTEMAS DIGITALES_2,9:00 - 11:00 | Martes
7,MA02,11310011,2.0,FUNDAMENTOS DE SISTEMAS DIGITALES,FUNDAMENTOS DE SISTEMAS DIGITALES_3,9:00 - 11:00 | Miércoles

In [114]:
solucion_df3 = generate_schedule(df_3, horarios_mañana)
solucion_df3.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310004,3.0,CALCULO 2,CALCULO 2_1,7:00 - 9:00 | Miércoles
1,MA02,11310004,3.0,CALCULO 2,CALCULO 2_2,7:00 - 9:00 | Jueves
2,MA02,11310017,3.0,INGENIERIA DE DATOS,INGENIERIA DE DATOS_1,9:00 - 11:00 | Lunes
3,MA02,11310017,3.0,INGENIERIA DE DATOS,INGENIERIA DE DATOS_2,9:00 - 11:00 | Martes
4,MA02,11310017,3.0,INGENIERIA DE DATOS,INGENIERIA DE DATOS_3,9:00 - 11:00 | Miércoles
5,MA02,11310032,3.0,CORNERSTONE PROJECT,CORNERSTONE PROJECT_1,7:00 - 9:00 | Viernes
6,MA02,11310031,3.0,PROBABILIDAD Y ESTADISTICA 1,PROBABILIDAD Y ESTADISTICA 1_1,9:00 - 11:00 | Jueves
7,MA02,11310031,3.0,PROBABILIDAD Y ESTADISTICA 1,PROBABILIDAD Y ESTADISTICA 1_2,9:00 - 11:00 | Viernes
8,MA02,11310031,3.0,PROBABILIDAD Y ESTADISTICA 1,PROBABILIDAD Y ESTADISTICA 1_3,11:00 - 13:00 | Lunes
9,MA02,11310030,3.0,ALGEBRA LINEAL,ALGEBRA LINEAL_1,7:00 - 9:00 | Lunes
10,MA02,11310030,3.0,ALGEBRA LINEAL,ALGEBRA LINEAL_2,7:00 - 9:00 | Martes

In [115]:
solucion_df4 = generate_schedule(df_4, horarios_mañana)
solucion_df4.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310014,4.0,TEORIA DE GRAFOS,TEORIA DE GRAFOS_1,9:00 - 11:00 | Martes
1,MA02,11310014,4.0,TEORIA DE GRAFOS,TEORIA DE GRAFOS_2,9:00 - 11:00 | Miércoles
2,MA02,11310033,4.0,PROBABILIDAD Y ESTADISTICA 2,PROBABILIDAD Y ESTADISTICA 2_1,7:00 - 9:00 | Viernes
3,MA02,11310033,4.0,PROBABILIDAD Y ESTADISTICA 2,PROBABILIDAD Y ESTADISTICA 2_2,9:00 - 11:00 | Lunes
4,MA02,11310036,4.0,CALCULO 3,CALCULO 3_1,7:00 - 9:00 | Lunes
5,MA02,11310012,4.0,OPTIMIZACION,OPTIMIZACION_1,7:00 - 9:00 | Martes
6,MA02,11310012,4.0,OPTIMIZACION,OPTIMIZACION_2,7:00 - 9:00 | Miércoles
7,MA02,11310012,4.0,OPTIMIZACION,OPTIMIZACION_3,7:00 - 9:00 | Jueves
8,MA02,11310007,4.0,TEORIA DE LA COMPUTACION,TEORIA DE LA COMPUTACION_1,9:00 - 11:00 | Jueves
9,MA02,11310007,4.0,TEORIA DE LA COMPUTACION,TEORIA DE LA COMPUTACION_2,9:00 - 11:00 | Viernes

In [116]:
solucion_df5 = generate_schedule(df_5, horarios_mañana)
solucion_df5.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310041,5.0,KEYSTONE PROJECT,KEYSTONE PROJECT_1,9:00 - 11:00 | Miércoles
1,MA02,11310034,5.0,ECUACIONES DIFERENCIALES,ECUACIONES DIFERENCIALES_1,9:00 - 11:00 | Lunes
2,MA02,11310034,5.0,ECUACIONES DIFERENCIALES,ECUACIONES DIFERENCIALES_2,9:00 - 11:00 | Martes
3,MA02,11310013,5.0,ANALISIS ESTADISTICO DE DATOS,ANALISIS ESTADISTICO DE DATOS_1,7:00 - 9:00 | Lunes
4,MA02,11310013,5.0,ANALISIS ESTADISTICO DE DATOS,ANALISIS ESTADISTICO DE DATOS_2,7:00 - 9:00 | Martes
5,MA02,11310013,5.0,ANALISIS ESTADISTICO DE DATOS,ANALISIS ESTADISTICO DE DATOS_3,7:00 - 9:00 | Miércoles
6,MA02,11310010,5.0,ANALISIS REAL,ANALISIS REAL_1,7:00 - 9:00 | Jueves
7,MA02,11310010,5.0,ANALISIS REAL,ANALISIS REAL_2,7:00 - 9:00 | Viernes

In [117]:
solucion_df6 = generate_schedule(df_6, horarios_mañana)
solucion_df6.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310018,6.0,ALGEBRA ABSTRACTA Y CODIFICACION,ALGEBRA ABSTRACTA Y CODIFICACION_1,7:00 - 9:00 | Lunes
1,MA02,11310018,6.0,ALGEBRA ABSTRACTA Y CODIFICACION,ALGEBRA ABSTRACTA Y CODIFICACION_2,7:00 - 9:00 | Martes
2,MA02,11310040,6.0,MODELING OF DYNAMICAL SYSTEMS,MODELING OF DYNAMICAL SYSTEMS_1,9:00 - 11:00 | Lunes
3,MA02,11310040,6.0,MODELING OF DYNAMICAL SYSTEMS,MODELING OF DYNAMICAL SYSTEMS_2,9:00 - 11:00 | Martes
4,MA02,11310040,6.0,MODELING OF DYNAMICAL SYSTEMS,MODELING OF DYNAMICAL SYSTEMS_3,9:00 - 11:00 | Miércoles
5,MA02,11310015,6.0,ELEMENTOS DE FISICA,ELEMENTOS DE FISICA_1,7:00 - 9:00 | Miércoles
6,MA02,11310015,6.0,ELEMENTOS DE FISICA,ELEMENTOS DE FISICA_2,7:00 - 9:00 | Jueves
7,MA02,11310015,6.0,ELEMENTOS DE FISICA,ELEMENTOS DE FISICA_3,7:00 - 9:00 | Viernes

In [118]:
solucion_df1 = generate_schedule(df_7, horarios_mañana)
solucion_df1.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310021,7.0,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA_1,7:00 - 9:00 | Lunes
1,MA02,11310021,7.0,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA,ANALISIS NUMERICO Y COMPUTACION CIENTIFICA_2,7:00 - 9:00 | Martes
2,MA02,11310053,7.0,GEOMETRIA COMPUTACIONAL Y DIFERENCIAL,GEOMETRIA COMPUTACIONAL Y DIFERENCIAL_1,7:00 - 9:00 | Miércoles
3,MA02,11310053,7.0,GEOMETRIA COMPUTACIONAL Y DIFERENCIAL,GEOMETRIA COMPUTACIONAL Y DIFERENCIAL_2,7:00 - 9:00 | Jueves
4,MA02,11310053,7.0,GEOMETRIA COMPUTACIONAL Y DIFERENCIAL,GEOMETRIA COMPUTACIONAL Y DIFERENCIAL_3,7:00 - 9:00 | Viernes
5,MA02,11310020,7.0,TOPOLOGIA,TOPOLOGIA_1,9:00 - 11:00 | Lunes
6,MA02,11310020,7.0,TOPOLOGIA,TOPOLOGIA_2,9:00 - 11:00 | Martes

In [119]:
solucion_df1 = generate_schedule(df_8, horarios_mañana)
solucion_df1.head(80)

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310029,8.0,CAPSTONE PROJECT,CAPSTONE PROJECT_1,7:00 - 9:00 | Lunes

In [149]:
final_df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8], axis=0)
final_df.reset_index(drop=True, inplace=True)
final_df.head()

,programa,codigo,semestre,asignatura,codificacion,horario
0,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,PROGRAMACION DE COMPUTADORES_1,9:00 - 11:00 | Lunes
1,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,PROGRAMACION DE COMPUTADORES_2,9:00 - 11:00 | Martes
2,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,PROGRAMACION DE COMPUTADORES_3,9:00 - 11:00 | Miércoles
3,MA02,11310044,1.0,PRECALCULO,PRECALCULO_1,7:00 - 9:00 | Jueves
4,MA02,11310044,1.0,PRECALCULO,PRECALCULO_2,7:00 - 9:00 | Viernes

In [150]:
final_df['Lunes'] = final_df['horario'].apply(lambda x: x.split('|')[0].strip() if 'Lunes' in x else "")
final_df['Martes'] = final_df['horario'].apply(lambda x: x.split('|')[0].strip() if 'Martes' in x else "")
final_df['Miércoles'] = final_df['horario'].apply(lambda x: x.split('|')[0].strip() if 'Miércoles' in x else "")
final_df['Jueves'] = final_df['horario'].apply(lambda x: x.split('|')[0].strip() if 'Jueves' in x else "")
final_df['Viernes'] = final_df['horario'].apply(lambda x: x.split('|')[0].strip() if 'Viernes' in x else "")
final_df.drop(columns=['codificacion', 'horario'], inplace=True)
final_df = final_df.groupby(['programa', 'codigo', 'semestre', 'asignatura'], as_index=False).agg(lambda x: ''.join(x.dropna()))
final_df = final_df.sort_values(by=['semestre', 'asignatura'])
final_df.head(20)

,programa,codigo,semestre,asignatura,Lunes,Martes,Miércoles,Jueves,Viernes
0,MA02,11310001,1.0,LOGICA TEORIA DE NUMEROS Y CONJUNTOS,7:00 - 9:00,7:00 - 9:00,,,
16,MA02,11310025,1.0,PENSAMIENTO MATEMATICO,,,7:00 - 9:00,,
26,MA02,11310044,1.0,PRECALCULO,,,,7:00 - 9:00,7:00 - 9:00
1,MA02,11310002,1.0,PROGRAMACION DE COMPUTADORES,9:00 - 11:00,9:00 - 11:00,9:00 - 11:00,,
4,MA02,11310006,2.0,ALGORITMOS Y ESTRUCTURAS DE DATOS,7:00 - 9:00,7:00 - 9:00,7:00 - 9:00,,
2,MA02,11310003,2.0,CALCULO 1,,,,7:00 - 9:00,7:00 - 9:00
7,MA02,11310011,2.0,FUNDAMENTOS DE SISTEMAS DIGITALES,9:00 - 11:00,9:00 - 11:00,9:00 - 11:00,,
18,MA02,11310030,3.0,ALGEBRA LINEAL,7:00 - 9:00,7:00 - 9:00,,,
3,MA02,11310004,3.0,CALCULO 2,,,7:00 - 9:00,7:00 - 9:00,
20,MA02,11310032,3.0,CORNERSTONE PROJECT,,,,,7:00 - 9:00
12,MA02,11310017,3.0,INGENIERIA DE DATOS,9:00 - 11:00,9:00 - 11:00,9:00 - 11:00,,
19,MA02,11310031,3.0,PROBABILIDAD Y ESTADISTICA 1,11:00 - 13:00,,,9:00 - 11:00,9:00 - 11:00
23,MA02,11310036,4.0,CALCULO 3,7:00 - 9:00,,,,
8,MA02,11310012,4.0,OPTIMIZACION,,7:00 - 9:00,7:00 - 9:00,7:00 - 9:00,
21,MA02,11310033,4.0,PROBABILIDAD Y ESTADISTICA 2,9:00 - 11:00,,,,7:00 - 9:00
10,MA02,11310014,4.0,TEORIA DE GRAFOS,,9:00 - 11:00,9:00 - 11:00,,
5,MA02,11310007,4.0,TEORIA DE LA COMPUTACION,,,,9:00 - 11:00,9:00 - 11:00
9,MA02,11310013,5.0,ANALISIS ESTADISTICO DE DATOS,7:00 - 9:00,7:00 - 9:00,7:00 - 9:00,,
6,MA02,11310010,5.0,ANALISIS REAL,,,,7:00 - 9:00,7:00 - 9:00
22,MA02,11310034,5.0,ECUACIONES DIFERENCIALES,9:00 - 11:00,9:00 - 11:00,,,

In [144]:
final_df.to_csv('pre_proyeccion.csv', index=False)